/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStatementsRouteImport } from './routes/dashboard/statements'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard/knowledge'
import { Route as DashboardCommitmentsRouteImport } from './routes/dashboard/commitments'
import { Route as DashboardBriefRouteImport } from './routes/dashboard/brief'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as ApiWebhooksGmailRouteImport } from './routes/api/webhooks/gmail'
import { Route as ApiWebhooksCalendarRouteImport } from './routes/api/webhooks/calendar'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStatementsReportRouteImport } from './routes/api/statements/report'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatementsRoute = DashboardStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommitmentsRoute = DashboardCommitmentsRouteImport.update({
  id: '/commitments',
  path: '/commitments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBriefRoute = DashboardBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGmailRoute = ApiWebhooksGmailRouteImport.update({
  id: '/api/webhooks/gmail',
  path: '/api/webhooks/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCalendarRoute = ApiWebhooksCalendarRouteImport.update({
  id: '/api/webhooks/calendar',
  path: '/api/webhooks/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatementsReportRoute = ApiStatementsReportRouteImport.update({
  id: '/api/statements/report',
  path: '/api/statements/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/brief': typeof DashboardBriefRoute
  '/dashboard/commitments': typeof DashboardCommitmentsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statements': typeof DashboardStatementsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/statements/report': typeof ApiStatementsReportRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/webhooks/calendar': typeof ApiWebhooksCalendarRoute
  '/api/webhooks/gmail': typeof ApiWebhooksGmailRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/brief': typeof DashboardBriefRoute
  '/dashboard/commitments': typeof DashboardCommitmentsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statements': typeof DashboardStatementsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/statements/report': typeof ApiStatementsReportRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/webhooks/calendar': typeof ApiWebhooksCalendarRoute
  '/api/webhooks/gmail': typeof ApiWebhooksGmailRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/brief': typeof DashboardBriefRoute
  '/dashboard/commitments': typeof DashboardCommitmentsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statements': typeof DashboardStatementsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/statements/report': typeof ApiStatementsReportRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/webhooks/calendar': typeof ApiWebhooksCalendarRoute
  '/api/webhooks/gmail': typeof ApiWebhooksGmailRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/unauthenticated'
    | '/dashboard/brief'
    | '/dashboard/commitments'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/'
    | '/api/auth/google'
    | '/api/auth/session'
    | '/api/auth/sign-out'
    | '/api/google/callback'
    | '/api/statements/report'
    | '/api/stripe/webhook'
    | '/api/webhooks/calendar'
    | '/api/webhooks/gmail'
    | '/profile/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/unauthenticated'
    | '/dashboard/brief'
    | '/dashboard/commitments'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard'
    | '/api/auth/google'
    | '/api/auth/session'
    | '/api/auth/sign-out'
    | '/api/google/callback'
    | '/api/statements/report'
    | '/api/stripe/webhook'
    | '/api/webhooks/calendar'
    | '/api/webhooks/gmail'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/unauthenticated'
    | '/dashboard/brief'
    | '/dashboard/commitments'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/'
    | '/api/auth/google'
    | '/api/auth/session'
    | '/api/auth/sign-out'
    | '/api/google/callback'
    | '/api/statements/report'
    | '/api/stripe/webhook'
    | '/api/webhooks/calendar'
    | '/api/webhooks/gmail'
    | '/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiStatementsReportRoute: typeof ApiStatementsReportRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWebhooksCalendarRoute: typeof ApiWebhooksCalendarRoute
  ApiWebhooksGmailRoute: typeof ApiWebhooksGmailRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/statements': {
      id: '/dashboard/statements'
      path: '/statements'
      fullPath: '/dashboard/statements'
      preLoaderRoute: typeof DashboardStatementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commitments': {
      id: '/dashboard/commitments'
      path: '/commitments'
      fullPath: '/dashboard/commitments'
      preLoaderRoute: typeof DashboardCommitmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brief': {
      id: '/dashboard/brief'
      path: '/brief'
      fullPath: '/dashboard/brief'
      preLoaderRoute: typeof DashboardBriefRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/gmail': {
      id: '/api/webhooks/gmail'
      path: '/api/webhooks/gmail'
      fullPath: '/api/webhooks/gmail'
      preLoaderRoute: typeof ApiWebhooksGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/calendar': {
      id: '/api/webhooks/calendar'
      path: '/api/webhooks/calendar'
      fullPath: '/api/webhooks/calendar'
      preLoaderRoute: typeof ApiWebhooksCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/statements/report': {
      id: '/api/statements/report'
      path: '/api/statements/report'
      fullPath: '/api/statements/report'
      preLoaderRoute: typeof ApiStatementsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBriefRoute: typeof DashboardBriefRoute
  DashboardCommitmentsRoute: typeof DashboardCommitmentsRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatementsRoute: typeof DashboardStatementsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBriefRoute: DashboardBriefRoute,
  DashboardCommitmentsRoute: DashboardCommitmentsRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatementsRoute: DashboardStatementsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiStatementsReportRoute: ApiStatementsReportRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWebhooksCalendarRoute: ApiWebhooksCalendarRoute,
  ApiWebhooksGmailRoute: ApiWebhooksGmailRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
